### ISSUE TITLE
Ошибка при удалении товара из корзины

### ISSUE THREAD

**Issue by olegpolyakov** [Alexzanderk/node-expert-vulkan#3]
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '[data-id=rokla-2.5t-inox]' is not a valid selector.
    at View.findListItemProduct (http://localhost:3001/js/app.js:576:37)
    at View.removeProduct (http://localhost:3001/js/app.js:614:38)
    at Controller.removeProduct (http://localhost:3001/js/app.js:719:19)
    at events.(anonymous function).forEach.listener (http://localhost:3001/js/app.js:87:51)
    at Array.forEach (<anonymous>)
    at View.emit (http://localhost:3001/js/app.js:87:31)
    at View.handleRemove (http://localhost:3001/js/app.js:594:14)
```

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Создание корзины](https://trello.com/c/XoT3F1n4/4-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D1%80%D0%B7%D0%B8%D0%BD%D1%8B)

**Comment by Alexzanderk** [comment]
ошибка не обнаружена, возможно исправлена в процессе доработки корзины
